resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: dapdev.azurecr.io/cdnos-controller
  newTag: detect-and-heal-partial-bcb3cdc
