resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
<<<<<<< HEAD
  newName: public.ecr.aws/dn/cdnos-controller
  newTag: "1.4"
=======
  newName: registry.dev.drivenets.net/devops/cdnos-controller
  newTag: "1.6"
>>>>>>> 432cb45 (add redis env var support)
