apiVersion: cdnos.dev.drivenets.net/v1
kind: Cdnos
metadata:
  labels:
    app.kubernetes.io/name: cdnos
    app.kubernetes.io/instance: cdnos-sample
    app.kubernetes.io/part-of: cdnos-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cdnos-controller
  name: cdnos-sample
spec:
  image: "pr-registry.dev.drivenets.net/cdnos:noam2"
  initImage: us-west1-docker.pkg.dev/kne-external/kne/networkop/init-wait:ga
  command: "/define_notif_net.sh"
  ports:
    gnmi:
      innerPort: 9339
      outerPort: 9339
    gribi:
      innerPort: 9340
      outerPort: 9340
  tls:
    selfSigned:
      commonName: "cdnos-sample"
      keySize: 2048